### ISSUE TITLE
Possible incorrect equation in jitter calculation

### ISSUE THREAD

**Issue by nora-anne** [brandondube/prysm#101]
The calculation of the jitter in `jitter_ft` in `degredations` uses `scale / 2` in the exponential equation. However, this give results in conflict with other methods I have used to calculate jitter. For example, [Genberg, Michels, Doyle](http://www.sigmadyne.com/sigweb/downloads/SPIE-8127-16.pdf) (sect 2.3) and [Pittelkau & McKinley 2012](https://arc.aiaa.org/doi/pdf/10.2514/6.2012-4869) (eqn 29c) both use a scale without a factor of 1/2. I am not an expert in this field, so it's possible I'm misunderstanding either the scale parameter used in the code or the literature, but it seems the factor of 1/2 in the code is in error.

**Comment by brandondube** [comment]
Thank you for this bug report, and #100.  The jitter normalization used in the revision of the code that you are using is from [Auelmann](https://www.cis.rit.edu/~rlepci/Image%20Quality%20Metrics.pdf).  Auelmann's choice of "units" (whether there is a factor of 2 in the gaussian in space, or in frequency) is older than Genberg et al, and was dominant in industry years ago.  As you surmise, the industry has changed to the notation used by Genberg et al, because it uses standard form gaussians as you would find in e.g. Abramowitz and Stegun.

[About two months ago, I changed the jitter ft function to use the more modern form, and also changed the smear ft from a polar coordinate for the input the Cartesian, where the smear is given as x and y magnitudes.](https://github.com/brandondube/prysm/blob/master/prysm/degredations.py)

If you find an issue with the current implementation on master, please do comment.  If there is no issue on master, perhaps we could close this issue?  I expect that by the end of the calendar year [~v1~](https://prysm.readthedocs.io/en/latest/releases/v1.0.html) v0.22 will be released.

**Comment by nora-anne** [comment]
Ah, that makes sense, thanks for the clarification!
