### ISSUE TITLE
Interface for class changes

### ISSUE THREAD

**Issue by brandondube** [brandondube/prysm#15]
There is sometimes a desire to hop between prysm classes.  For example, convert a Wavefront to a Convolvable instance.  An elegant way to implement this, in terms of API, is to have a single to or from method that takes a class to convert to, and returns that class:

```python
from prysm import Pupil, Wavefront, Interferogram, PSF

# any of these will work for this, since they all inherit from basicdata, 
# most of the other classes would work too.
pu = Pupil()
wvfrnt = Wavefront()
interf = Interferogram()

# interface 1 -- _to
pu_i = pu.to(Interferogram) # pu_i is an interferogram instance with the data from pu

# interface 2 -- from
pu_i = Interferogram.from(pu) # the same
```
these interfaces have a similar level of verbosity, and would use some reflection magic to be implemented, but it is not that hard.  The .from is more like the typical prysm syntax -- PSF.from_pupil, MTF.from_psf, etc. So on the one hand, it is more consistent.  On the other, from_pupil and from_psf both do work make this transformation, while the generic class changers above wouldn't.

There is also the option 3 of just refactoring as much as possible into BasicData, but I kind of feel that some things, e.g. encircled energy or PVr, belong explicitly to one class.

Perhaps there is another possible interface design?

**Comment by JulesScholler** [comment]
I liked the way it worked with different object being from different classes, so I agree with you that option 3 is probably not the best in this case. Physically these are really different object and will behave differently depending on several parameters (e.g. coherence/partial coherence/incoherence). Also it is probably more flexible and clear that way if you want to add a method for only one object. Same goes if you want to add another object.

Then I wonder, do you really need to have both possibilities 'from' and 'to' since it is redondant. I feel like you always want to create a physical object _from_ another rather than converting it _to_ another. Maybe it is sufficient to implement this 'from' magic method, so if someone wants to convert a pupil to a wavefront then he could only use:

> pu = Pupil()
> wvt = Wavefront.from(pu)

This will probably be easier to maintain if you want to change the converting method as it will exist only in one place.

**Comment by brandondube** [comment]
`from` vs. `to` is a "one of" or "either or" thing -- it is just grammar between the two, since they each have access to the same info when called.

A rudimentary implementation of `from` would be:

```python
import inspect

def convert_class(from_, to):
    sig = inspect.signature(to.__init__)
    kwarg_pass = {}
    for kw in sig.kwargs:
        if hasattr(from_, kw) and kw not in ('x', 'y'):
            kwarg_pass[kw] = getattr(from_, kw)

    data = getattr(from_, from._data_attr, None)
    return to(data=data, x=from_.x, y=from_.y, **kwarg_pass)
```

There would need to be a bit more to gloss over details of different classes, but the core would be as above.

**Comment by JulesScholler** [comment]
Ok that make sense!

**Comment by brandondube** [comment]
Come to think of it, `.astype` from numpy and numpy-descendent libraries is probably a good way to go.

**Comment by brandondube** [comment]
some work in 569200e89b9c5ea946708378b687d7ff0456f857 - enough to beta test

**Comment by brandondube** [comment]
good enough for .19, need user feedback to improve
