### ISSUE TITLE
MTF result from FringeZernike pupil is diffraction limited?

### ISSUE THREAD

**Issue by jonathanabishop** [brandondube/prysm#24]
I'm attempting to calculate the aberrated MTF using a pupil defined using FringeZernike. In this particular case, it has only first order defocus. I expect the result to match closely with Hopkins' solution (or Shannon's approximation). Plotting the pupil function and printing the output from the Pupil object, I have the expected amount of defocus, but the MTF that's plotted is the classic diffraction-limited MTF. A prysm-specific snippet that plots using the variables I've separately calculated for Shannon's approximation is below.

If I'm missing something in the implementation, I apologize, but it looks after several reviews like the inputs are consistent with what I want and what prysm wants.

Any assistance is appreciated.
```
prysmWavelength = system_wavelength * 1.0E9 # Convert wavelength to nm
prysmDiameter = system_aperture_diameter * 1000.0 # Convert diameter to mm
prysmDefocus = prysmWavelength * system_W_pp # Convert to nm
prysmPupil = FringeZernike(wavelength = prysmWavelength, dia = prysmDiameter, samples=5000, Z4 = prysmDefocus / 2.0) # Set defocus coefficient to 1/2 of peak-to-peak value
print(prysmPupil)
prysmPupil.plot2d()
prysmMTF = MTF.from_pupil(prysmPupil, prysmDiameter * system_f_number, Q=2)

fig, (ax1, ax2) = plt.subplots(ncols=2,figsize=(10,4))
prysmMTF.slices().plot('x', fig=fig, ax=ax1)
```

**Comment by brandondube** [comment]
What version are you using, 0.17.x?

When I re-wrote the "header" to your code as:
```python
system_wavelength = 500e-9 # meters
system_aperture_diameter = 100e-3 # meters
system_W_pp = 1 # waves, expect a zero at the center of the PSF
system_f_number = 10

prysmWavelength = system_wavelength * 1e6
prysmDiameter = system_aperture_diameter * 1000
prysmDefocus = prysmWavelength * system_W_pp
```

I'm assuming W_pp is supposed to be a Hopkins coefficient (W020).  In the algebra, with the example of unity, this spits out 0.5 for prysmDefocus, which is interpreted as 0.5 nm, since the default `z_unit` argument is `nm`.

For debugging things like this, the print is likely helpful:
```python

>>> print(prysmPupil)
Fringe Zernike description with:
	+0.250 Z4 - Defocus
	0.496 PV, 0.144 RMS [nm]
```

You could change your call that looks like:
```python
prysmPupil = FringeZernike(\
                           wavelength=prysmWavelength,
                           dia=prysmDiameter,
                           samples=50,
                           Z4=prysmDefocus/2)
```

to:

```python
prysmPupil = FringeZernike(\
                           wavelength=prysmWavelength,
                           dia=prysmDiameter,
                           samples=50,
                           Z4=prysmDefocus/2,
                           z_unit='um') # <- see this line
```


As an aside, as well, 5,000 samples is very very large and you can get away with far smaller numbers, like the default of 128, unless you have a monstrous amount of OPD, care about things very far away in the spatial/PSF domain, or need the fidelity to be extremely high (back of a napkin, you should get to 1e-13 level with 5,000 samples).

The accuracy will actually turn around eventually due to floating point overflow.  I know 10,000x10,000 is too many samples for complex doubles if the signal has a scale much bigger than unity.

As an aside2, "raw" numeric wavelengths in prysm are given in microns; if you are ever unsure about a unit, the docstring (in this case, `help(prysm.Pupil)` will tell you, or you can use an astropy quantity, as in:

```python
from prysm import FringeZernike
from astropy import units as u

FringeZernike(wavelength = 500 * u.nm)
```

Of course this doesn't really matter for the purposes of the issue, since the wavelength just changes the coordinates of the MTF.


----

Did you look at the user's guide for [Zernikes](https://prysm.readthedocs.io/en/stable/user_guide/Zernikes.html) and [Pupils](https://prysm.readthedocs.io/en/stable/user_guide/Pupils.html)?  If so, was anything unclear?  How about the API documentation (things like `help(prysmPupil)`?  If anything was unclear, could you please open a PR to improve the docs?

**Comment by jonathanabishop** [comment]
Thank you for the quick reply.

I've found the issue--I had seen that Pupils have default z_units of nm, and missed that the default wavelengths are in um. Everything else was fine.

As an aside, I found samples=129 more pleasing since it then includes a point at the center and gives print(prysmPupil) then gives exactly the expected PV value.

**Comment by brandondube** [comment]
128 vs 129 accuracy just has to do with even vs odd numbers of samples.  In the even case, you can have a point at one extreme or the other - so you end up a bit shy on one side.  Powers of two should have better performance, but that is very old advise that I've never bothered to test.
