### ISSUE TITLE
Adding polarization utility

### ISSUE THREAD

**Issue by Jashcraf** [brandondube/prysm#89]
Jones and Mueller calculus may be useful for prysm going forward. [I started a branch](https://github.com/Jashcraf/prysm/blob/experimental_polarization/prysm/experimental/polarization.py) to add jones calculus, jones to mueller matrix conversion, and pauli spin matrices to prysm under prysm/experimental. 

Seeking feedback on the structure of the code for rapid matrix multiplication. Everything is built on the` _empty_jones()` function so that the jones matrices are generally N x 2 x 2, to allow for matrix multiplications to be broadcasted instead of looped over.

**Comment by brandondube** [comment]
A few comments:

- please swap `import numpy as np` -> `from .mathops import np` (eventually) / `from prysm.mathops import np` (experimental purgatory).  This is all that is required for GPU support
- docstrings in Numpy style start with a capital and begin on the line immediately below `def`.  So, e.g., `"""returns an empty array to populate with jones matrix elements` move this up one line, start with capital R, and end first line with a period.  The pydocstyle linter will show you these in your editor
- line 30: prefer `dtype=config.precision_complex` instead of `'complex128'`, unless polarization arithmetic is highly sensitive to numerical precision
- using lists and append for shapes is a bit weird, since Numpy gives tuples; this may be more numpythonic (new word?) as, e.g., `if shape is None: shape = (2,2); else: shape = (*shape, 2, 2)`
- for performance, prefer `cost = np.cos(t); sint = np.sin(t); jones[...,0,1] = cost`.  trig functions are actually super expensive - sin(x) and fft(x) are about comparable up to 1024x1024.
- As a v0/v1, assigning to the last [0,1] is fine for now.  My rewrite of the thin film code to do that is ~30% slower than the move axis shenanigans I have in there now.  It may be faster to create the matrix with the elements on the first two dimensions, and then shuffle them into the back dimensions after with moveaxis/swapaxis.  Benchmark before doing that though, in all senses (is faster on this func significant overall, and if it is x% faster, is it also 25x% less legible).
- line 254 -- I think prysm just about universally uses ValueError for what this assert is used for.  The assert is actually buggy as-is, python's assert syntax is still kind of python 2-y.  `assert condition` will blow up if condition is falsy.  All non-empty strings are truth, i.e. `assert ''` is the only assert on a falsy string, that will blow up.  Any other `assert 'mystring'` does not blow up.  If you did want to use an assert, you would move the assert to before your three conditions, and do `assert index in (0,1,2,3), f"index should be 0,1,2, or 3. Got {index}"`.  A two-clause assert (`assert condition`) raises an empty assertion error.  A three clause assertion (`assert condition 'WHY')` raises an assertion error, whose message is `'WHY'`.

The rest looks good!

**Comment by Jashcraf** [comment]
Awesome, changes made and I started a pull request. We can keep this issue open / start a new one to discuss adding the moveaxis shenanigans?

**Comment by brandondube** [comment]
Let's use a separate issue for move axis stuff, since it's a performance enhancement instead of a new feature
